version: '3'
services:
  web:
    image: nginx
    restart: always
    volumes:
      - ./index/index.html:/usr/share/nginx/html/index.html:ro
  auth:
    image: beevelop/nginx-basic-auth
    links:
      - fluentd
      - web
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: nginx.access
    ports:
      - "80:80"
  fluentd:
    build: ./logging
    volumes:
      - ./logging/conf:/fluentd/etc
    links:
      - "mongo"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: nginx_logs
    volumes:
      - ./data/db/mongo:/data/db
